---
title: "Data Products Leaflet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Seven Wonders of the Ancient World
#### November 3, 2018

```{r, message = FALSE}
library(leaflet, warn.conflicts = F)
# Coordinates from https://latitude.to/ and https://www.findlatitudeandlongitude.com/
pyramid <- c(29.97416777, 31.1339477975, "Great Pyramid of Giza")
hangingGardens <- c(32.5355, 44.4275, "Hanging Gardens of Babylon")
colossus <- c(36.450664864, 28.22333244, "Colossus of Rhodes")
lighthouse <- c(31.15458, 29.84587, "Lighthouse of Alexandria")
temple <- c(37.943162894, 27.3583319, "Temple of Artemis")
statue <- c(37.6360474558, 21.624664168, "Statue of Zeus at Olympia")
mausoleum <- c(37.0360998556, 27.4210983156, "Mausoleum at Halicarnasus")

df <- data.frame(rbind(pyramid, hangingGardens, colossus, lighthouse, temple, 
                       statue, mausoleum))
names(df) <- c("lat", "lng", "popup")
df$lat <- as.numeric(as.character(df$lat))
df$lng <- as.numeric(as.character(df$lng))
df$popup <- as.character(df$popup)

df %>% leaflet() %>% addTiles() %>% addMarkers(popup = df$popup)
```

